import { afterEach, describe, expect, it, vi } from "vitest";
import { resolveHetangOpsConfig } from "./config.js";
import { lookupStructuredMemberRecallCandidates } from "./customer-query.js";
import { executePhoneSuffixCustomerProfileQuery } from "./customer-profile.js";

function buildConfig(overrides: Record<string, unknown> = {}) {
  return resolveHetangOpsConfig({
    api: {
      appKey: "demo-app-key",
      appSecret: "demo-app-secret",
    },
    database: {
      url: "postgresql://hetang:secret@127.0.0.1:5432/hetang_ops",
    },
    stores: [
      {
        orgId: "1001",
        storeName: "迎宾店",
        rawAliases: ["迎宾"],
      },
    ],
    ...overrides,
  });
}

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("lookupStructuredMemberRecallCandidates", () => {
  it("builds a structured payload for tool-facing member recall lookup", async () => {
    const config = buildConfig();

    const result = await lookupStructuredMemberRecallCandidates({
      runtime: {
        listMemberReactivationQueue: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              memberCardNo: "8888",
              referenceCode: "13800008888",
              primarySegment: "important-reactivation-member",
              followupBucket: "high-value-reactivation",
              reactivationPriorityScore: 781.4,
              strategyPriorityScore: 812.2,
              executionPriorityScore: 826.8,
              priorityBand: "P0",
              priorityRank: 1,
              churnRiskLabel: "critical",
              churnRiskScore: 0.93,
              revisitWindowLabel: "due-now",
              recommendedActionLabel: "immediate-1to1",
              recommendedTouchWeekday: "Friday",
              recommendedTouchDaypart: "late-night",
              touchWindowLabel: "best-today",
              reasonSummary: "高价值会员已沉默 19 天，余额正在下滑。",
              touchAdviceSummary: "今晚 21:00 后一对一关怀，优先约熟悉技师。",
              daysSinceLastVisit: 19,
              visitCount90d: 6,
              payAmount90d: 2680,
              currentStoredBalanceInferred: 780,
              projectedBalanceDaysLeft: 24,
              birthdayMonthDay: "04-15",
              nextBirthdayBizDate: "2026-04-15",
              birthdayWindowDays: 5,
              birthdayBoostScore: 18,
              topTechName: "王技师",
              queueJson: "{}",
              updatedAt: "2026-04-10T08:00:00+08:00",
            },
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M002",
              customerIdentityKey: "member:M002",
              customerDisplayName: "李女士",
              memberCardNo: "9999",
              referenceCode: "13800009999",
              primarySegment: "potential-growth-customer",
              followupBucket: "potential-growth",
              reactivationPriorityScore: 620.5,
              strategyPriorityScore: 631.8,
              executionPriorityScore: 640.3,
              priorityBand: "P1",
              priorityRank: 2,
              churnRiskLabel: "high",
              churnRiskScore: 0.72,
              revisitWindowLabel: "due-this-week",
              recommendedActionLabel: "growth-nurture",
              recommendedTouchWeekday: "Sunday",
              recommendedTouchDaypart: "afternoon",
              touchWindowLabel: "best-this-week",
              reasonSummary: "近 90 天已有消费，适合继续培育。",
              touchAdviceSummary: "周末下午发关怀券，顺带约下次到店。",
              daysSinceLastVisit: 11,
              visitCount90d: 4,
              payAmount90d: 1260,
              currentStoredBalanceInferred: 380,
              projectedBalanceDaysLeft: 18,
              birthdayMonthDay: null,
              nextBirthdayBizDate: null,
              birthdayWindowDays: null,
              birthdayBoostScore: 0,
              topTechName: "陈技师",
              queueJson: "{}",
              updatedAt: "2026-04-10T08:10:00+08:00",
            },
          ] as never,
        listMemberReactivationFeatures: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              memberCardNo: "8888",
              referenceCode: "13800008888",
              primarySegment: "important-reactivation-member",
              daysSinceLastVisit: 19,
              visitCount30d: 1,
              visitCount90d: 6,
              payAmount30d: 0,
              payAmount90d: 2680,
              memberPayAmount30d: 0,
              memberPayAmount90d: 1800,
              rechargeTotal30d: 0,
              rechargeTotal90d: 1200,
              rechargeCount30d: 0,
              rechargeCount90d: 1,
              daysSinceLastRecharge: 63,
              currentStoredBalanceInferred: 780,
              storedBalance7dAgo: 980,
              storedBalance30dAgo: 1560,
              storedBalance90dAgo: 2180,
              storedBalanceDelta7d: -200,
              storedBalanceDelta30d: -780,
              storedBalanceDelta90d: -1400,
              depletionVelocity30d: 26,
              projectedBalanceDaysLeft: 24,
              rechargeToMemberPayRatio90d: 0.66,
              dominantVisitDaypart: "late-night",
              preferredDaypartShare90d: 0.67,
              dominantVisitWeekday: "Friday",
              preferredWeekdayShare90d: 0.5,
              dominantVisitMonthPhase: "mid-month",
              preferredMonthPhaseShare90d: 0.44,
              weekendVisitShare90d: 0.58,
              lateNightVisitShare90d: 0.67,
              overnightVisitShare90d: 0.11,
              averageVisitGapDays90d: 13.6,
              visitGapStddevDays90d: 3.2,
              cycleDeviationScore: 0.18,
              timePreferenceConfidenceScore: 0.74,
              trajectoryConfidenceScore: 0.78,
              reactivationPriorityScore: 781.4,
              featureJson: "{}",
            },
          ] as never,
        listMemberReactivationStrategies: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              primarySegment: "important-reactivation-member",
              reactivationPriorityScore: 781.4,
              churnRiskScore: 0.93,
              churnRiskLabel: "critical",
              revisitProbability7d: 0.31,
              revisitWindowLabel: "due-now",
              recommendedTouchWeekday: "Friday",
              recommendedTouchDaypart: "late-night",
              touchWindowMatchScore: 0.82,
              touchWindowLabel: "best-today",
              lifecycleMomentumScore: 0.26,
              lifecycleMomentumLabel: "cooling",
              recommendedActionLabel: "immediate-1to1",
              strategyPriorityScore: 812.2,
              strategyJson: "{}",
            },
          ] as never,
      },
      config,
      orgId: "1001",
      bizDate: "2026-04-10",
      limit: 1,
    });

    expect(result).toMatchObject({
      org_id: "1001",
      store_name: "迎宾店",
      snapshot_biz_date: "2026-04-10",
      total_candidates: 2,
      candidates: [
        {
          member_id: "M001",
          customer_name: "张女士",
          priority_band: "P0",
          followup_bucket: "high-value-reactivation",
          recommended_action: "immediate-1to1",
          recommended_touch: {
            weekday: "Friday",
            daypart: "late-night",
            label: "best-today",
          },
          time_pattern: {
            dominant_daypart: "late-night",
            dominant_weekday: "Friday",
          },
          strategy: {
            churn_risk_label: "critical",
            revisit_window_label: "due-now",
            lifecycle_momentum_label: "cooling",
          },
          birthday: {
            next_birthday_biz_date: "2026-04-15",
            birthday_window_days: 5,
          },
          top_tech_name: "王技师",
        },
      ],
    });
    expect(result.candidates).toHaveLength(1);
  });

  it("adds bounded strategy ai advisory without changing deterministic queue ranking", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: async () => ({
          choices: [
            {
              message: {
                content: JSON.stringify({
                  contactAngle: "以熟悉技师和近期余额消耗为切入点做一对一关怀。",
                  talkingPoints: ["先提熟悉技师档期", "再提近期放松恢复需求"],
                  offerGuardrails: ["不要先发通用大额券"],
                  doNotPushFlags: ["避免群发式话术"],
                }),
              },
            },
          ],
        }),
      }),
    );

    const config = buildConfig({
      customerGrowthAi: {
        enabled: true,
        baseUrl: "https://customer-growth.example.com/v1",
        apiKey: "growth-secret",
        model: "gpt-5-mini",
        timeoutMs: 3200,
        profileInsight: { enabled: false },
        tagAdvisor: { enabled: false },
        strategyAdvisor: { enabled: true },
        followupSummarizer: { enabled: false },
      },
    });

    const result = await lookupStructuredMemberRecallCandidates({
      runtime: {
        listMemberReactivationQueue: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              memberCardNo: "8888",
              referenceCode: "13800008888",
              primarySegment: "important-reactivation-member",
              followupBucket: "high-value-reactivation",
              reactivationPriorityScore: 781.4,
              strategyPriorityScore: 812.2,
              executionPriorityScore: 826.8,
              priorityBand: "P0",
              priorityRank: 1,
              churnRiskLabel: "critical",
              churnRiskScore: 0.93,
              revisitWindowLabel: "due-now",
              recommendedActionLabel: "immediate-1to1",
              recommendedTouchWeekday: "Friday",
              recommendedTouchDaypart: "late-night",
              touchWindowLabel: "best-today",
              reasonSummary: "高价值会员已沉默 19 天，余额正在下滑。",
              touchAdviceSummary: "今晚 21:00 后一对一关怀，优先约熟悉技师。",
              daysSinceLastVisit: 19,
              visitCount90d: 6,
              payAmount90d: 2680,
              currentStoredBalanceInferred: 780,
              projectedBalanceDaysLeft: 24,
              birthdayMonthDay: "04-15",
              nextBirthdayBizDate: "2026-04-15",
              birthdayWindowDays: 5,
              birthdayBoostScore: 18,
              topTechName: "王技师",
              queueJson: "{}",
              updatedAt: "2026-04-10T08:00:00+08:00",
            },
          ] as never,
        listMemberReactivationFeatures: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              memberCardNo: "8888",
              referenceCode: "13800008888",
              primarySegment: "important-reactivation-member",
              daysSinceLastVisit: 19,
              visitCount30d: 1,
              visitCount90d: 6,
              payAmount30d: 0,
              payAmount90d: 2680,
              memberPayAmount30d: 0,
              memberPayAmount90d: 1800,
              rechargeTotal30d: 0,
              rechargeTotal90d: 1200,
              rechargeCount30d: 0,
              rechargeCount90d: 1,
              daysSinceLastRecharge: 63,
              currentStoredBalanceInferred: 780,
              storedBalance7dAgo: 980,
              storedBalance30dAgo: 1560,
              storedBalance90dAgo: 2180,
              storedBalanceDelta7d: -200,
              storedBalanceDelta30d: -780,
              storedBalanceDelta90d: -1400,
              depletionVelocity30d: 26,
              projectedBalanceDaysLeft: 24,
              rechargeToMemberPayRatio90d: 0.66,
              dominantVisitDaypart: "late-night",
              preferredDaypartShare90d: 0.67,
              dominantVisitWeekday: "Friday",
              preferredWeekdayShare90d: 0.5,
              dominantVisitMonthPhase: "mid-month",
              preferredMonthPhaseShare90d: 0.44,
              weekendVisitShare90d: 0.58,
              lateNightVisitShare90d: 0.67,
              overnightVisitShare90d: 0.11,
              averageVisitGapDays90d: 13.6,
              visitGapStddevDays90d: 3.2,
              cycleDeviationScore: 0.18,
              timePreferenceConfidenceScore: 0.74,
              trajectoryConfidenceScore: 0.78,
              reactivationPriorityScore: 781.4,
              featureJson: "{}",
            },
          ] as never,
        listMemberReactivationStrategies: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              primarySegment: "important-reactivation-member",
              reactivationPriorityScore: 781.4,
              churnRiskScore: 0.93,
              churnRiskLabel: "critical",
              revisitProbability7d: 0.31,
              revisitWindowLabel: "due-now",
              recommendedTouchWeekday: "Friday",
              recommendedTouchDaypart: "late-night",
              touchWindowMatchScore: 0.82,
              touchWindowLabel: "best-today",
              lifecycleMomentumScore: 0.26,
              lifecycleMomentumLabel: "cooling",
              recommendedActionLabel: "immediate-1to1",
              strategyPriorityScore: 812.2,
              strategyJson: "{}",
            },
          ] as never,
      },
      config,
      orgId: "1001",
      bizDate: "2026-04-10",
      limit: 1,
    });

    expect(result.candidates[0]).toMatchObject({
      member_id: "M001",
      priority_band: "P0",
      priority_rank: 1,
      ai_advisory: {
        strategy_advisor: {
          contact_angle: "以熟悉技师和近期余额消耗为切入点做一对一关怀。",
          talking_points: ["先提熟悉技师档期", "再提近期放松恢复需求"],
          offer_guardrails: ["不要先发通用大额券"],
          do_not_push_flags: ["避免群发式话术"],
        },
      },
    });
    expect(result.candidates[0]?.priority_band).toBe("P0");
    expect(result.candidates[0]?.scores.execution_priority).toBe(826.8);
  });

  it("renders operating profile snapshot and evidence boundaries in phone-suffix profile text", async () => {
    const config = buildConfig();

    const text = await executePhoneSuffixCustomerProfileQuery({
      runtime: {
        findCurrentMembersByPhoneSuffix: async () =>
          [
            {
              orgId: "1001",
              memberId: "M001",
              name: "张女士",
              phone: "13800008888",
              storedAmount: 1280,
              consumeAmount: 3680,
              lastConsumeTime: "2026-04-10 20:15:00",
              silentDays: 3,
              rawJson: "{}",
            },
          ] as never,
        listCurrentMembers: async () =>
          [
            {
              orgId: "1001",
              memberId: "M001",
              name: "张女士",
              phone: "13800008888",
              storedAmount: 1280,
              consumeAmount: 3680,
              lastConsumeTime: "2026-04-10 20:15:00",
              silentDays: 3,
              rawJson: "{}",
            },
          ] as never,
        listCurrentMemberCards: async () => [] as never,
        listConsumeBillsByDateRange: async () => [] as never,
        listTechMarketByDateRange: async () => [] as never,
        listCustomerSegments: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              customerIdentityKey: "member:M001",
              customerIdentityType: "member",
              customerDisplayName: "张女士",
              memberId: "M001",
              memberCardNo: "8888",
              referenceCode: "13800008888",
              memberLabel: "金卡",
              identityStable: true,
              segmentEligible: true,
              firstBizDate: "2025-10-01",
              lastBizDate: "2026-04-10",
              daysSinceLastVisit: 3,
              visitCount30d: 2,
              visitCount90d: 6,
              payAmount30d: 980,
              payAmount90d: 3680,
              memberPayAmount90d: 2400,
              groupbuyAmount90d: 0,
              directPayAmount90d: 1280,
              distinctTechCount90d: 2,
              topTechCode: "T001",
              topTechName: "王技师",
              topTechVisitCount90d: 4,
              topTechVisitShare90d: 0.67,
              recencySegment: "active-30d",
              frequencySegment: "medium-2-3",
              monetarySegment: "high-1000-plus",
              paymentSegment: "mixed-member-nonmember",
              techLoyaltySegment: "single-tech-loyal",
              primarySegment: "important-reactivation-member",
              tagKeys: ["important-reactivation-member"],
              rawJson: "{}",
            },
          ] as never,
        listCustomerProfile90dByDateRange: async () =>
          [
            {
              orgId: "1001",
              windowEndBizDate: "2026-04-10",
              customerIdentityKey: "member:M001",
              customerIdentityType: "member",
              customerDisplayName: "张女士",
              memberId: "M001",
              memberCardNo: "8888",
              referenceCode: "13800008888",
              identityStable: true,
              segmentEligible: true,
              daysSinceLastVisit: 3,
              visitCount30d: 2,
              visitCount90d: 6,
              payAmount30d: 980,
              payAmount90d: 3680,
              memberPayAmount90d: 2400,
              groupbuyAmount90d: 0,
              directPayAmount90d: 1280,
              distinctTechCount90d: 2,
              topTechCode: "T001",
              topTechName: "王技师",
              topTechVisitCount90d: 4,
              topTechVisitShare90d: 0.67,
              recencySegment: "active-30d",
              frequencySegment: "medium-2-3",
              monetarySegment: "high-1000-plus",
              paymentSegment: "mixed-member-nonmember",
              techLoyaltySegment: "single-tech-loyal",
              primarySegment: "important-reactivation-member",
              tagKeys: ["important-reactivation-member"],
              currentStoredAmount: 1280,
              currentConsumeAmount: 3680,
              currentLastConsumeTime: "2026-04-10 20:15:00",
              currentSilentDays: 3,
            },
          ] as never,
        listCustomerOperatingProfilesDaily: async () =>
          [
            {
              orgId: "1001",
              bizDate: "2026-04-10",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              customerDisplayName: "张女士",
              identityProfileJson: { member_name: "张女士" },
              spendingProfileJson: { pay_amount_90d: 3680 },
              serviceNeedProfileJson: {
                primary_need: "肩颈放松",
                signal_confidence: "high",
              },
              interactionProfileJson: {
                communication_style: "少聊天",
                confidence_discount: 0.35,
              },
              preferenceProfileJson: { preferred_daypart: "夜场" },
              scenarioProfileJson: { dominant_visit_daypart: "night" },
              relationshipProfileJson: { top_tech_name: "王技师" },
              opportunityProfileJson: { reactivation_priority_score: 612 },
              sourceSignalIds: ["signal-1", "signal-2", "signal-3"],
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
          ] as never,
        listCustomerOperatingSignals: async () =>
          [
            {
              signalId: "signal-1",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              signalDomain: "service_need",
              signalKey: "primary_need",
              valueText: "肩颈放松",
              valueJson: { confidence_discount: 0 },
              confidence: "high",
              truthBoundary: "hard_fact",
              scoringScope: "profile_allowed",
              sourceObservationIds: ["obs-1", "obs-2"],
              supportCount: 2,
              observedAt: "2026-04-10T18:00:00.000Z",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
            {
              signalId: "signal-2",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              signalDomain: "interaction_style",
              signalKey: "communication_style",
              valueText: "少聊天",
              valueJson: { confidence_discount: 0.35 },
              confidence: "medium",
              truthBoundary: "observed_fact",
              scoringScope: "action_only",
              sourceObservationIds: ["obs-3"],
              supportCount: 1,
              observedAt: "2026-04-10T18:10:00.000Z",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
            {
              signalId: "signal-3",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              signalDomain: "contact_preference",
              signalKey: "preferred_channel",
              valueText: "企微",
              valueJson: { confidence_discount: 0.65 },
              confidence: "low",
              truthBoundary: "predicted_signal",
              scoringScope: "action_only",
              sourceObservationIds: ["obs-4"],
              supportCount: 1,
              observedAt: "2026-04-10T18:20:00.000Z",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
          ] as never,
        listCustomerServiceObservations: async () =>
          [
            {
              observationId: "obs-1",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              sourceRole: "technician",
              sourceType: "self_reported",
              signalDomain: "service_need",
              signalKey: "primary_need",
              valueText: "肩颈放松",
              confidence: "high",
              truthBoundary: "hard_fact",
              observedAt: "2026-04-10T18:00:00.000Z",
              rawNote: "客户明确说最近肩颈很紧",
              rawJson: "{}",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
            {
              observationId: "obs-2",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              sourceRole: "technician",
              sourceType: "staff_observed",
              signalDomain: "service_need",
              signalKey: "primary_need",
              valueText: "肩颈放松",
              confidence: "medium",
              truthBoundary: "observed_fact",
              observedAt: "2026-04-10T18:01:00.000Z",
              rawNote: "按肩颈时明显紧张",
              rawJson: "{}",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
            {
              observationId: "obs-3",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              sourceRole: "technician",
              sourceType: "staff_observed",
              signalDomain: "interaction_style",
              signalKey: "communication_style",
              valueText: "少聊天",
              confidence: "medium",
              truthBoundary: "observed_fact",
              observedAt: "2026-04-10T18:10:00.000Z",
              rawNote: "服务过程中更喜欢安静",
              rawJson: "{}",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
            {
              observationId: "obs-4",
              orgId: "1001",
              memberId: "M001",
              customerIdentityKey: "member:M001",
              sourceRole: "system",
              sourceType: "system_inferred",
              signalDomain: "contact_preference",
              signalKey: "preferred_channel",
              valueText: "企微",
              confidence: "low",
              truthBoundary: "predicted_signal",
              observedAt: "2026-04-10T18:20:00.000Z",
              rawNote: "系统推测更适合企微触达",
              rawJson: "{}",
              updatedAt: "2026-04-10T20:00:00.000Z",
            },
          ] as never,
      },
      config,
      intent: {
        rawText: "迎宾店尾号8888客户画像",
        kind: "customer_profile",
        explicitOrgIds: ["1001"],
        allStoresRequested: false,
        timeFrame: {
          kind: "range",
          startBizDate: "2026-01-12",
          endBizDate: "2026-04-10",
          label: "近90天",
          days: 90,
        },
        phoneSuffix: "8888",
        metrics: [],
        unsupportedMetrics: [],
        mentionsCompareKeyword: false,
        mentionsRankingKeyword: false,
        mentionsTrendKeyword: false,
        mentionsAnomalyKeyword: false,
        mentionsRiskKeyword: false,
        mentionsAdviceKeyword: false,
        mentionsReportKeyword: false,
        routeConfidence: "high",
        semanticSlots: {
          store: {
            scope: "single",
            orgIds: ["1001"],
          },
          object: "customer",
          action: "profile",
          metricKeys: [],
          time: {
            kind: "range",
            startBizDate: "2026-01-12",
            endBizDate: "2026-04-10",
            label: "近90天",
            days: 90,
          },
        },
      } as never,
      effectiveOrgIds: ["1001"],
      now: new Date("2026-04-10T20:00:00+08:00"),
    });

    expect(text).toContain("经营画像补充");
    expect(text).toContain("服务诉求：肩颈放松");
    expect(text).toContain("观察线索");
    expect(text).toContain("互动风格：观察偏向少聊天");
    expect(text).toContain("推断线索");
    expect(text).toContain("触达偏好：可能更接受企微");
    expect(text).not.toContain("客户明确说最近肩颈很紧");
  });
});
