import type { SemanticFrontdoorLane } from "./semantic-frontdoor-classifier.js";
import type { SemanticOsiDomain } from "./semantic-osi-contracts.js";

export type SemanticQuestionBindingDomain =
  | SemanticOsiDomain
  | "hq"
  | "brand"
  | "marketing"
  | "management"
  | "system"
  | "external";

export type SemanticQuestionAnswerMode =
  | "metric_snapshot"
  | "comparison"
  | "ranked_list"
  | "segment_list"
  | "analysis_brief"
  | "boundary_reply"
  | "action_loop"
  | "semantic_asset_draft"
  | "knowledge_answer"
  | "brand_plan";

export type SemanticQuestionBinding = {
  id: string;
  family: string;
  domain: SemanticQuestionBindingDomain;
  osi_domain?: SemanticOsiDomain;
  frontdoor_lane: SemanticFrontdoorLane;
  sample_questions: string[];
  capability_id: string | null;
  metric_refs: string[];
  segment_refs: string[];
  recipe_refs: string[];
  requires_store: boolean;
  requires_time: boolean;
  requires_metric: boolean;
  answer_mode: SemanticQuestionAnswerMode;
};

type BindingSeed = Omit<SemanticQuestionBinding, "sample_questions"> & {
  sample: string;
};

function bind(seed: BindingSeed): SemanticQuestionBinding {
  return {
    ...seed,
    sample_questions: [seed.sample],
  };
}

const STORE_DATA_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_store_daily_revenue",
    family: "单店日营收",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天营收多少",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:daily_cash_in"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_customer_count",
    family: "单店日客流",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店昨天来了多少人",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_total_clock",
    family: "单店日钟数",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天总钟数多少",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:total_clock_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_average_ticket",
    family: "单店日客单价",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天客单价多少",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:order_average_ticket"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_clock_effect",
    family: "单店日钟效",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天钟效多少",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:tech_clock_efficiency"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_point_clock_rate",
    family: "单店日点钟率",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天点钟率怎么样",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:point_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_add_clock_rate",
    family: "单店日加钟率",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店昨天加钟率怎么样",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:add_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_cash_performance",
    family: "单店日现金业绩",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天真实到账多少",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:cash_performance"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_daily_recharge_cash",
    family: "单店日充值现金",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天充值现金多少",
    capability_id: "store_day_summary_v1",
    metric_refs: ["metric:recharge_cash"],
    segment_refs: [],
    recipe_refs: ["analysis:recharge_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_recharge_bonus",
    family: "充值赠送比",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店本月充值赠送多不多",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:recharge_total_with_bonus", "metric:recharge_bonus_value"],
    segment_refs: [],
    recipe_refs: ["analysis:recharge_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_stored_balance",
    family: "门店储值余额",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店会员卡里还压着多少钱",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:stored_balance"],
    segment_refs: ["segment:silent_member_with_balance"],
    recipe_refs: ["analysis:member_churn_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_discount_pressure",
    family: "折扣压力",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店最近折扣有没有失控",
    capability_id: "store_anomaly_v1",
    metric_refs: ["metric:member_discount_amount", "metric:member_discount_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:anti_settle_anomaly_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_anti_settle_risk",
    family: "反结异常",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店最近有没有反结异常",
    capability_id: "store_anomaly_v1",
    metric_refs: ["metric:anti_settle_amount"],
    segment_refs: [],
    recipe_refs: ["analysis:anti_settle_anomaly_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_period_compare_revenue",
    family: "营收跨期对比",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店这周比上周营收怎么样",
    capability_id: "store_compare_v1",
    metric_refs: ["metric:daily_cash_in"],
    segment_refs: [],
    recipe_refs: ["analysis:week_vs_last_week_store"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "comparison",
  }),
  bind({
    id: "qf_store_period_compare_customer",
    family: "客流跨期对比",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店本月客流比上月强还是弱",
    capability_id: "store_compare_v1",
    metric_refs: ["metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:month_vs_last_month_store"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "comparison",
  }),
  bind({
    id: "qf_store_trend_revenue",
    family: "营收趋势",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店最近三个月营收趋势怎么样",
    capability_id: "store_trend_v1",
    metric_refs: ["metric:daily_cash_in"],
    segment_refs: [],
    recipe_refs: ["analysis:month_vs_last_month_store"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_trend_recharge",
    family: "充值趋势",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店最近充值是不是变弱了",
    capability_id: "store_trend_v1",
    metric_refs: ["metric:recharge_cash"],
    segment_refs: [],
    recipe_refs: ["analysis:recharge_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_health_review",
    family: "单店经营健康",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店近7天经营健康吗",
    capability_id: "store_risk_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_action_advice",
    family: "单店动作建议",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店近7天重点抓什么",
    capability_id: "store_advice_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "action_loop",
  }),
  bind({
    id: "qf_store_daily_report",
    family: "单店日报",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天日报",
    capability_id: "store_report_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count", "metric:recharge_cash"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_clock_breakdown",
    family: "钟数结构拆解",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨日钟数是怎么构成的",
    capability_id: "store_day_clock_breakdown_v1",
    metric_refs: ["metric:total_clock_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_market_breakdown",
    family: "副项销售结构",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店今天卖出什么副项了",
    capability_id: "store_market_breakdown_v1",
    metric_refs: ["metric:market_revenue"],
    segment_refs: [],
    recipe_refs: ["analysis:market_attach_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_groupbuy_revisit",
    family: "团购复到店",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店团购客回头了吗",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:groupbuy_revisit_rate"],
    segment_refs: ["segment:groupbuy_revisit_customer"],
    recipe_refs: ["analysis:groupbuy_conversion_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_new_member",
    family: "新增会员",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天新增会员多少",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:new_member_count"],
    segment_refs: ["segment:first_visit_new_customer"],
    recipe_refs: ["analysis:first_visit_conversion_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_attendance_rate",
    family: "门店出勤率",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店4月技师出勤率多少",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:attendance_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:shift_capacity_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_full_attendance",
    family: "满勤人数",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店4月满勤人数多少",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:full_attendance_people"],
    segment_refs: [],
    recipe_refs: ["analysis:shift_capacity_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_labor_performance",
    family: "劳动业绩",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店3月劳动业绩多少",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:total_labor_performance"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_store_received_labor_performance",
    family: "实收劳动业绩",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店3月实收劳动业绩多少",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:received_labor_performance"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "metric_snapshot",
  }),
];

const CUSTOMER_DATA_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_customer_high_balance_sleeping",
    family: "高余额沉睡会员",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店哪些会员余额高但很久没来了",
    capability_id: "customer_ranked_list_lookup_v1",
    metric_refs: ["metric:stored_balance"],
    segment_refs: ["segment:high_balance_silent_customer"],
    recipe_refs: ["analysis:member_churn_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_customer_sleeping_members",
    family: "沉睡会员名单",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店哪些客人很久没来了",
    capability_id: "customer_segment_list_v1",
    metric_refs: [],
    segment_refs: ["segment:sleeping_customer"],
    recipe_refs: ["analysis:member_churn_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "segment_list",
  }),
  bind({
    id: "qf_customer_silent_with_balance",
    family: "有余额沉默会员",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店有余额但不来的客人有多少",
    capability_id: "customer_segment_list_v1",
    metric_refs: ["metric:stored_balance"],
    segment_refs: ["segment:silent_member_with_balance"],
    recipe_refs: ["analysis:member_churn_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "segment_list",
  }),
  bind({
    id: "qf_customer_high_value_members",
    family: "高价值会员",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店最高价值的前10个客人是谁",
    capability_id: "customer_ranked_list_lookup_v1",
    metric_refs: [],
    segment_refs: ["segment:high_value_member"],
    recipe_refs: ["analysis:customer_profile_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_customer_recharge_not_visited",
    family: "充值未到店",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店谁充了钱还没来过",
    capability_id: "customer_segment_list_v1",
    metric_refs: ["metric:recharge_cash"],
    segment_refs: ["segment:recharge_not_visited_member"],
    recipe_refs: ["analysis:recharge_activation_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "segment_list",
  }),
  bind({
    id: "qf_customer_groupbuy_revisit_candidates",
    family: "团购二访候选",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店团购新客哪些值得跟进二访",
    capability_id: "customer_segment_list_v1",
    metric_refs: ["metric:groupbuy_revisit_rate"],
    segment_refs: ["segment:groupbuy_revisit_customer"],
    recipe_refs: ["analysis:groupbuy_conversion_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "segment_list",
  }),
  bind({
    id: "qf_customer_first_visit_followup",
    family: "新客未二访",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店上周新来的客人有没有第二次到店",
    capability_id: "customer_segment_list_v1",
    metric_refs: ["metric:new_member_count"],
    segment_refs: ["segment:first_visit_new_customer"],
    recipe_refs: ["analysis:first_visit_conversion_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "segment_list",
  }),
  bind({
    id: "qf_customer_birthday_window",
    family: "生日窗口会员",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店明天过生日的高价值会员有哪些",
    capability_id: "birthday_member_list_v1",
    metric_refs: [],
    segment_refs: ["segment:high_value_member"],
    recipe_refs: ["analysis:birthday_window_followup_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_customer_coupon_unused",
    family: "优惠券未核销",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "迎宾店上次发的券有多少人用了",
    capability_id: "member_marketing_analysis_v1",
    metric_refs: [],
    segment_refs: ["segment:coupon_received_unused_customer"],
    recipe_refs: ["analysis:coupon_redemption_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_customer_source_silence",
    family: "会员来源沉默",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店哪种来源的会员更容易沉默",
    capability_id: "member_marketing_analysis_v1",
    metric_refs: [],
    segment_refs: ["segment:sleeping_customer"],
    recipe_refs: ["analysis:customer_profile_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_customer_profile_lookup",
    family: "客户画像查询",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店尾号3456的顾客画像",
    capability_id: "customer_profile_lookup_v1",
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:customer_profile_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_customer_arrival_pattern",
    family: "客户到店时段偏好",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店客人一般几点来",
    capability_id: "arrival_profile_timeseries_v1",
    metric_refs: ["metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:arrival_pattern_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_customer_followup_queue",
    family: "今日客户跟进队列",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店今天要联系哪些客人",
    capability_id: "customer_ranked_list_lookup_v1",
    metric_refs: [],
    segment_refs: ["segment:high_value_member", "segment:sleeping_customer"],
    recipe_refs: ["analysis:customer_followup_task_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "action_loop",
  }),
  bind({
    id: "qf_customer_reactivation_script",
    family: "客户唤回动作",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店高余额沉睡会员怎么唤回",
    capability_id: "customer_ranked_list_lookup_v1",
    metric_refs: ["metric:stored_balance"],
    segment_refs: ["segment:high_balance_silent_customer"],
    recipe_refs: ["analysis:customer_followup_task_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "action_loop",
  }),
  bind({
    id: "qf_customer_tech_dependency",
    family: "客户技师绑定风险",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "如果小李离职，会影响哪些高余额客户",
    capability_id: "customer_relation_lookup_v1",
    metric_refs: ["metric:stored_balance"],
    segment_refs: ["segment:tech_loyal_customer"],
    recipe_refs: ["analysis:tech_dependency_risk_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_customer_relation_history",
    family: "顾客技师关系轨迹",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "某个客人换过哪些技师",
    capability_id: "customer_relation_lookup_v1",
    metric_refs: [],
    segment_refs: ["segment:tech_loyal_customer"],
    recipe_refs: ["analysis:tech_dependency_risk_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
];

const TECHNICIAN_DATA_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_tech_revenue_ranking",
    family: "技师营收排行",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店昨天哪个技师最赚钱",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:tech_service_revenue"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_earnings_fairness_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_tech_clock_effect_ranking",
    family: "技师钟效排行",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店人效最高的技师是谁",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:tech_clock_efficiency"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_earnings_fairness_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_tech_point_clock_ranking",
    family: "技师点钟排行",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店点钟率最高的技师是谁",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:tech_point_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_tech_add_clock_ranking",
    family: "技师加钟排行",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店加钟率最高的技师是谁",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:add_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_tech_market_revenue_ranking",
    family: "技师副项排行",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店今天谁推销做得好",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:market_revenue"],
    segment_refs: [],
    recipe_refs: ["analysis:market_attach_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_tech_profile",
    family: "技师画像",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店技师白慧慧的画像",
    capability_id: "tech_profile_lookup_v1",
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_tech_current_on_clock",
    family: "当前上钟技师",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店现在几个人在上钟",
    capability_id: "tech_current_runtime_v1",
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:realtime_floor_state"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "metric_snapshot",
  }),
  bind({
    id: "qf_tech_current_idle",
    family: "当前空闲技师",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店哪些技师现在有空",
    capability_id: "tech_current_runtime_v1",
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:realtime_floor_state"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_tech_low_conversion",
    family: "技师产能异常",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店哪些技师上钟多但加钟弱",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:total_clock_count", "metric:add_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_tech_customer_dependency",
    family: "技师客户依赖",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店哪个技师绑定高余额客户最多",
    capability_id: "customer_relation_lookup_v1",
    metric_refs: ["metric:stored_balance"],
    segment_refs: ["segment:tech_loyal_customer"],
    recipe_refs: ["analysis:tech_dependency_risk_review"],
    requires_store: true,
    requires_time: false,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_tech_commission_rate",
    family: "技师提成占比",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店技师提成占比高不高",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:tech_service_revenue"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_earnings_fairness_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_tech_shift_capacity",
    family: "技师班次供给",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店今晚人手够不够",
    capability_id: "tech_current_runtime_v1",
    metric_refs: ["metric:attendance_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:shift_capacity_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
];

const HQ_DATA_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_hq_five_store_overview",
    family: "五店经营全景",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "这几天五店怎么样",
    capability_id: "hq_portfolio_overview_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_hq_focus_store",
    family: "总部重点门店",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "五店近7天重点看什么",
    capability_id: "hq_portfolio_focus_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: false,
    answer_mode: "action_loop",
  }),
  bind({
    id: "qf_hq_risk_radar",
    family: "五店风险雷达",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "哪家店最危险",
    capability_id: "hq_portfolio_risk_v1",
    metric_refs: ["metric:daily_cash_in"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_hq_revenue_ranking",
    family: "五店营收排名",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "昨天各店营收排名",
    capability_id: "hq_window_ranking_v1",
    metric_refs: ["metric:daily_cash_in"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_hq_customer_ranking",
    family: "五店客流排名",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "昨天各店客流排名",
    capability_id: "hq_window_ranking_v1",
    metric_refs: ["metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_hq_recharge_ranking",
    family: "五店充值排名",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "本月各店充值排名",
    capability_id: "store_window_ranking_v1",
    metric_refs: ["metric:recharge_cash"],
    segment_refs: [],
    recipe_refs: ["analysis:recharge_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_hq_monthly_trend",
    family: "五店月度趋势",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "五店最近三个月趋势如何",
    capability_id: "hq_monthly_trend_report_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:month_vs_last_month_store"],
    requires_store: false,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_hq_deep_review",
    family: "五店深度复盘",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "五店近30天经营复盘并给指导意见",
    capability_id: "portfolio_store_review_async_v1",
    metric_refs: ["metric:daily_cash_in", "metric:customer_count", "metric:recharge_cash"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
];

const SEMANTIC_ASSET_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_asset_customer_tag_osi",
    family: "客户标签 OSI 草案",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "semantic_asset_design",
    sample: "客户标签 OSI 草案",
    capability_id: null,
    metric_refs: [],
    segment_refs: ["segment:high_balance_silent_customer", "segment:groupbuy_revisit_customer"],
    recipe_refs: ["analysis:customer_followup_task_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_member_tag_system",
    family: "会员标签体系",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "semantic_asset_design",
    sample: "会员标签体系怎么设计",
    capability_id: null,
    metric_refs: [],
    segment_refs: ["segment:sleeping_customer", "segment:high_value_member"],
    recipe_refs: ["analysis:customer_profile_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_customer_action_relation",
    family: "客户标签到动作关系",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "semantic_asset_design",
    sample: "客户标签怎么用于会员唤回",
    capability_id: null,
    metric_refs: [],
    segment_refs: ["segment:high_balance_silent_customer"],
    recipe_refs: ["analysis:customer_followup_task_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_technician_osi",
    family: "技师 OSI 草案",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "semantic_asset_design",
    sample: "技师评价 OSI 草案",
    capability_id: null,
    metric_refs: ["metric:tech_service_revenue", "metric:tech_point_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_store_osi",
    family: "门店 OSI 草案",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "semantic_asset_design",
    sample: "门店 OSI 文件怎么分域",
    capability_id: null,
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_metric_contract",
    family: "指标 contract 注册",
    domain: "system",
    frontdoor_lane: "semantic_asset_design",
    sample: "新指标如何进入 metric contract",
    capability_id: null,
    metric_refs: ["metric:daily_cash_in"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_recipe_contract",
    family: "经营 recipe 注册",
    domain: "system",
    frontdoor_lane: "semantic_asset_design",
    sample: "经营诊断 recipe 应该怎么定义",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_capability_graph",
    family: "Capability Graph 设计",
    domain: "system",
    frontdoor_lane: "semantic_asset_design",
    sample: "capability graph 和语义层如何绑定",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_answerability_gate",
    family: "回答前自检机制",
    domain: "system",
    frontdoor_lane: "semantic_asset_design",
    sample: "answerability gate 应该怎么设计",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
  bind({
    id: "qf_asset_data_coverage_gate",
    family: "数据覆盖 gate",
    domain: "system",
    frontdoor_lane: "semantic_asset_design",
    sample: "数据覆盖 gate 如何影响问答",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "semantic_asset_draft",
  }),
];

const METHODOLOGY_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_method_store_world_model",
    family: "门店世界模型",
    domain: "store",
    frontdoor_lane: "methodology_concept",
    sample: "门店的世界模型如何搭建",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_method_ai_physical_model",
    family: "AI 物理模型",
    domain: "store",
    frontdoor_lane: "methodology_concept",
    sample: "门店的 AI 物理模型如何定义",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_method_store_review",
    family: "经营复盘方法",
    domain: "store",
    frontdoor_lane: "methodology_concept",
    sample: "什么是门店经营复盘",
    capability_id: null,
    metric_refs: ["metric:daily_cash_in", "metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_method_point_clock_definition",
    family: "点钟率定义",
    domain: "store",
    frontdoor_lane: "methodology_concept",
    sample: "点钟率是什么意思",
    capability_id: null,
    metric_refs: ["metric:point_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_method_add_clock_definition",
    family: "加钟率定义",
    domain: "store",
    frontdoor_lane: "methodology_concept",
    sample: "加钟率是什么意思",
    capability_id: null,
    metric_refs: ["metric:add_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_method_clock_effect_definition",
    family: "钟效定义",
    domain: "store",
    frontdoor_lane: "methodology_concept",
    sample: "钟效怎么理解",
    capability_id: null,
    metric_refs: ["metric:tech_clock_efficiency"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
];

const KNOWLEDGE_AND_BRAND_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_book_huayuhua_apply",
    family: "华与华理论应用",
    domain: "marketing",
    frontdoor_lane: "book_knowledge_qa",
    sample: "华与华理论如何用于荷塘悦色",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_book_marketing_summary",
    family: "营销书方法提炼",
    domain: "marketing",
    frontdoor_lane: "book_knowledge_qa",
    sample: "这本营销书有哪些能落到门店的动作",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:customer_followup_task_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_book_management_action",
    family: "管理书动作转化",
    domain: "management",
    frontdoor_lane: "book_knowledge_qa",
    sample: "管理书里的方法怎么变成店长动作",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:shift_capacity_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_book_brand_to_store",
    family: "品牌书到门店经营",
    domain: "marketing",
    frontdoor_lane: "book_knowledge_qa",
    sample: "品牌书里的方法如何用于门店获客",
    capability_id: null,
    metric_refs: ["metric:customer_count"],
    segment_refs: ["segment:first_visit_new_customer"],
    recipe_refs: ["analysis:first_visit_conversion_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "knowledge_answer",
  }),
  bind({
    id: "qf_brand_positioning_plan",
    family: "品牌定位全案",
    domain: "brand",
    frontdoor_lane: "brand_marketing_plan",
    sample: "用华与华理论做品牌策划全案",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "brand_plan",
  }),
  bind({
    id: "qf_brand_super_symbol",
    family: "超级符号设计",
    domain: "brand",
    frontdoor_lane: "brand_marketing_plan",
    sample: "荷塘悦色超级符号怎么设计",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "brand_plan",
  }),
  bind({
    id: "qf_brand_slogan",
    family: "品牌口号",
    domain: "brand",
    frontdoor_lane: "brand_marketing_plan",
    sample: "荷塘悦色品牌口号怎么提炼",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "brand_plan",
  }),
  bind({
    id: "qf_brand_store_growth_plan",
    family: "门店增长营销方案",
    domain: "brand",
    frontdoor_lane: "brand_marketing_plan",
    sample: "给荷塘悦色设计一套门店增长营销方案",
    capability_id: null,
    metric_refs: ["metric:customer_count", "metric:groupbuy_revisit_rate"],
    segment_refs: ["segment:first_visit_new_customer"],
    recipe_refs: ["analysis:groupbuy_conversion_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "brand_plan",
  }),
  bind({
    id: "qf_external_competitor_research",
    family: "竞品研究",
    domain: "external",
    frontdoor_lane: "external_research",
    sample: "帮我做长风拨筋这个品牌的竞品分析",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "boundary_reply",
  }),
  bind({
    id: "qf_external_business_area",
    family: "周边商圈研究",
    domain: "external",
    frontdoor_lane: "external_research",
    sample: "门店周边商业行情怎么获取",
    capability_id: null,
    metric_refs: ["metric:customer_count"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "boundary_reply",
  }),
  bind({
    id: "qf_external_public_opinion",
    family: "口碑舆情研究",
    domain: "external",
    frontdoor_lane: "external_research",
    sample: "周边竞品口碑和团购销量怎么分析",
    capability_id: null,
    metric_refs: [],
    segment_refs: [],
    recipe_refs: ["analysis:groupbuy_conversion_review"],
    requires_store: false,
    requires_time: false,
    requires_metric: false,
    answer_mode: "boundary_reply",
  }),
];

const ADDITIONAL_DATA_BINDINGS: SemanticQuestionBinding[] = [
  bind({
    id: "qf_store_cash_vs_labor_performance",
    family: "现金业绩与劳动业绩对照",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店3月现金业绩和劳动业绩分别多少",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:cash_performance", "metric:received_labor_performance"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "comparison",
  }),
  bind({
    id: "qf_store_member_discount_review",
    family: "会员优惠诊断",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店最近会员优惠率是不是变高了",
    capability_id: "store_anomaly_v1",
    metric_refs: ["metric:member_discount_amount", "metric:member_discount_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:anti_settle_anomaly_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_market_attach_review",
    family: "副项转化诊断",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店副项推销有没有问题",
    capability_id: "store_market_breakdown_v1",
    metric_refs: ["metric:market_revenue"],
    segment_refs: [],
    recipe_refs: ["analysis:market_attach_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_store_groupbuy_7d_conversion",
    family: "团购 7 天转化",
    domain: "store",
    osi_domain: "store",
    frontdoor_lane: "store_data_query",
    sample: "义乌店团购客7天复到店率怎么样",
    capability_id: "store_metric_summary_v1",
    metric_refs: ["metric:groupbuy_revisit_rate"],
    segment_refs: ["segment:groupbuy_revisit_customer"],
    recipe_refs: ["analysis:groupbuy_conversion_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: true,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_customer_coupon_expiring_followup",
    family: "优惠券临期跟进",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店还有多少券快过期了没用",
    capability_id: "member_marketing_analysis_v1",
    metric_refs: [],
    segment_refs: ["segment:coupon_received_unused_customer"],
    recipe_refs: ["analysis:coupon_redemption_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "action_loop",
  }),
  bind({
    id: "qf_customer_high_value_activity",
    family: "高价值会员活跃度",
    domain: "customer",
    osi_domain: "customer",
    frontdoor_lane: "store_data_query",
    sample: "义乌店高价值会员最近活不活跃",
    capability_id: "customer_segment_list_v1",
    metric_refs: [],
    segment_refs: ["segment:high_value_member"],
    recipe_refs: ["analysis:customer_profile_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "analysis_brief",
  }),
  bind({
    id: "qf_tech_zero_clock_alert",
    family: "技师零上钟提醒",
    domain: "technician",
    osi_domain: "technician",
    frontdoor_lane: "store_data_query",
    sample: "义乌店今天谁还没开过单",
    capability_id: "tech_leaderboard_ranking_v1",
    metric_refs: ["metric:total_clock_count"],
    segment_refs: [],
    recipe_refs: ["analysis:tech_daily_state_review"],
    requires_store: true,
    requires_time: true,
    requires_metric: false,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_hq_point_clock_ranking",
    family: "五店点钟率排名",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "昨天各店点钟率排名",
    capability_id: "hq_window_ranking_v1",
    metric_refs: ["metric:point_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
  bind({
    id: "qf_hq_add_clock_ranking",
    family: "五店加钟率排名",
    domain: "hq",
    frontdoor_lane: "store_data_query",
    sample: "昨天各店加钟率排名",
    capability_id: "hq_window_ranking_v1",
    metric_refs: ["metric:add_clock_rate"],
    segment_refs: [],
    recipe_refs: ["analysis:store_health_review"],
    requires_store: false,
    requires_time: true,
    requires_metric: true,
    answer_mode: "ranked_list",
  }),
];

const SEMANTIC_QUESTION_BINDINGS: SemanticQuestionBinding[] = [
  ...STORE_DATA_BINDINGS,
  ...CUSTOMER_DATA_BINDINGS,
  ...TECHNICIAN_DATA_BINDINGS,
  ...HQ_DATA_BINDINGS,
  ...SEMANTIC_ASSET_BINDINGS,
  ...METHODOLOGY_BINDINGS,
  ...KNOWLEDGE_AND_BRAND_BINDINGS,
  ...ADDITIONAL_DATA_BINDINGS,
];

function clone<T>(value: T): T {
  return structuredClone(value);
}

export function listSemanticQuestionBindings(): SemanticQuestionBinding[] {
  return clone(SEMANTIC_QUESTION_BINDINGS);
}
